name:                language
version:             0.1.0.0
github:              "jallibad/language"
license:             ""
author:              "Jordan Alligood"
copyright:           "2018 Jordan Alligood"

ghc-options:
- -Wall
- -fno-warn-tabs
- -Werror

dependencies:
- base
- text
- bytestring
- vector
- mtl
- safe-exceptions
- time
- network
- cpu
- random
- optparse-applicative
- sized
- type-natural
- megaparsec
- containers
- parser-combinators
- binary
- singletons
- split
- monad-loops
- bimap
- conduit
- exceptions
- template-haskell

default-extensions:
- TupleSections
- LambdaCase
- MultiWayIf
- TypeOperators
- OverloadedStrings
- OverloadedLists
- ViewPatterns
- PatternSynonyms
- ExplicitForAll
- TypeApplications
- ScopedTypeVariables
- RankNTypes
- LiberalTypeSynonyms
- NamedFieldPuns
- RecordWildCards
- FlexibleInstances
- FlexibleContexts
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- GeneralizedNewtypeDeriving
- InstanceSigs
- ConstrainedClassMethods
- MultiParamTypeClasses
- FunctionalDependencies
- DeriveGeneric
- NamedWildCards
- PartialTypeSignatures
- ExistentialQuantification
- GADTSyntax
- GADTs
- TypeFamilies
- TypeFamilyDependencies
- AllowAmbiguousTypes
- KindSignatures
- ConstraintKinds
- DataKinds
- PolyKinds
- TypeInType
- EmptyCase
- StandaloneDeriving
- DefaultSignatures
- DeriveAnyClass
- DerivingStrategies
- DisambiguateRecordFields
- DuplicateRecordFields
- OverloadedLabels
- BangPatterns
- ApplicativeDo
- NegativeLiterals
- NumDecimals
- BinaryLiterals
- QuasiQuotes
- UnicodeSyntax
- NoMonomorphismRestriction
- PostfixOperators
- PackageImports

library:
  source-dirs: src/

tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -fno-warn-orphans
    dependencies:
      - language
      - hspec
      - QuickCheck
      - smallcheck
      - hspec-smallcheck

benchmarks:
  benchmark:
    main: Main.hs
    source-dirs: benchmark
    dependencies:
      - language
      - criterion

executables:
  language:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N